openapi: 3.0.0
info:
  title: Shop App
  description: |
    API provides possibility ....
  version: 1.0.0

servers:
  - url: http://localhost:8000/api
    description: Local host for debugging

path:
  /products/{product_id}:
    get:
      parameters:
        - name: product_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  description:
                    type: string
                  price:
                    type: number
                  category:
                    type: integer
          400:
            description: Non-exist product id
paths:

